import { Link } from 'react-router-dom'
import { Microscope, People, Book1, Tree, Global, LampCharge } from 'iconsax-react'
import { Arrow } from '../components/Arrow'
import { Reveal } from '../components/Reveal'
import { FoodTicker } from '../components/Ticker'

const imageUrl = 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1200&q=85'
const labUrl = 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=85'

export function Home() {
  const work = [['01', 'Research', 'Open-access research that moves alternative proteins forward.', '/research', Microscope], ['02', 'Education', 'Making the science of tomorrow accessible to everyone.', '/course', Book1], ['03', 'Community', 'A generous, inclusive space for ambitious people to connect.', '/about/team', People]] as const
  return <main>
    <section className="hero shell" id="top"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-line" /> Research · Education · Community</div><h1>Reimagining<br /><em>what’s possible.</em></h1><p className="hero-lede">We are a student-led community at the University of Waterloo accelerating the future of food through alternative protein innovation.</p><Link className="button button-dark" to="/about/who-we-are">Discover our work <Arrow /></Link></div><div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-image"><img src={imageUrl} alt="Close-up of green plant leaves" /></div><div className="hero-sticker">Food<br />for thought <span>✳</span></div><div className="hero-caption">01 / A living system<br /><span>Designing with nature</span></div></div></section>
    <FoodTicker />
    <section className="intro shell"><Reveal className="section-label">01 <span /> WHO WE ARE</Reveal><Reveal className="intro-grid"><h2>Good food should<br /><span>do more.</span></h2><div className="intro-body"><p className="large-copy">We’re building a future where food is better for people, animals, and the planet.</p><p>Waterloo Alt Protein Project is a student design team bringing together curious minds across science, engineering, mathematics, and beyond. Together, we make space for new ideas to grow.</p><Link to="/about/who-we-are" className="text-link">Meet the community <Arrow /></Link></div></Reveal></section>
    <section className="work-section"><div className="shell"><Reveal className="section-label light">02 <span /> OUR WORK</Reveal><Reveal className="work-heading"><h2>Small shifts.<br /><em>Massive impact.</em></h2><p>There is no single answer to the world’s biggest challenges. That’s why we work across disciplines to find many.</p></Reveal><div className="work-grid">{work.map(([number, title, description, to, Icon]) => <Reveal className="work-card" key={title}><div className="card-top"><span>{number}</span><Arrow /></div><div><div className="card-icon"><Icon size={38} variant="Linear" /></div><h3>{title}</h3><p>{description}</p></div><Link to={to}>Explore <Arrow /></Link></Reveal>)}</div></div></section>
    <section className="research shell"><Reveal className="research-image"><img src={labUrl} alt="Researcher working in a laboratory" /><span className="image-note">Research in motion<br /><b>Waterloo · Canada</b></span></Reveal><Reveal className="research-copy"><div className="section-label">03 <span /> IN THE LAB</div><h2>Curiosity is<br /><em>our compass.</em></h2><p>With 5+ professors and 10+ students across three faculties, our interdisciplinary team is raising the bar for cultivated seafood research.</p><div className="stat-row"><div><strong>700k<span>+</span></strong><small>CAD raised</small></div><div><strong>10<span>+</span></strong><small>Student researchers</small></div></div><Link className="text-link" to="/research">Read our research <Arrow /></Link></Reveal></section>
    <section className="principles"><div className="shell"><Reveal className="section-label light">04 <span /> HOW WE WORK</Reveal><Reveal className="principle-grid">{[[Tree, 'Think beyond', 'We look for solutions that work with nature, not against it.'], [Global, 'Keep it open', 'Knowledge creates more impact when everyone can build on it.'], [LampCharge, 'Stay curious', 'The best questions often lead somewhere unexpected.']].map(([Icon, title, text]) => <article className="principle-card" key={title as string}><Icon color="currentColor" size={30} variant="Linear" /><h3>{title as string}</h3><p>{text as string}</p></article>)}</Reveal></div></section>
    <section className="impact shell"><Reveal className="section-label">05 <span /> THE BIGGER PICTURE</Reveal><Reveal className="impact-grid"><div><h2>Food is a<br /><em>shared future.</em></h2></div><div><p>Alternative proteins give us a chance to rethink how food is made, who gets to shape it, and what a thriving planet can look like.</p><div className="impact-points"><div><strong>01</strong><span>Better for the planet</span></div><div><strong>02</strong><span>Better for people</span></div><div><strong>03</strong><span>Better by design</span></div></div></div></Reveal></section>
    <section className="contact" id="contact"><div className="shell contact-inner"><Reveal><div className="eyebrow"><span className="eyebrow-line" /> Stay curious</div><h2>Let’s make<br /><em>something better.</em></h2><p>Have an idea, a question, or just want to say hello?</p><Link className="button button-light" to="/contact">Start a conversation <Arrow /></Link></Reveal><div className="contact-mark">◎</div></div></section>
  </main>
}
