import type { ReactNode } from 'react'

export type PageData = { eyebrow: string; title: ReactNode; intro: string; paragraphs: string[]; source: string; image?: string }
const imageUrl = 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1200&q=85'
const labUrl = 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=85'

export const pageData: Record<string, PageData> = {
  '/about/who-we-are': { eyebrow: 'About · Who we are', title: <>A better food system<br /><em>starts with us.</em></>, intro: 'There is an urgent need to turn away from traditional livestock meats and make room for better ways to nourish people.', paragraphs: ['Waterloo Alt Protein Project is a student design team where curious minds come together to implement the Good Food Institute’s core objectives through projects that can create positive change.', 'We believe alternative proteins can help build a food system that is more sustainable, secure, humane, and resilient.'], source: 'https://www.altprotein.ca/who-we-are', image: imageUrl },
  '/about/team': { eyebrow: 'About · Our team', title: <>Many disciplines.<br /><em>One shared table.</em></>, intro: 'Our community brings together students, researchers, designers, and builders from across the University of Waterloo.', paragraphs: ['Our team spans mathematics, engineering, science, and the humanities. Every perspective helps us ask better questions and make the future of food more accessible.', 'We are always looking for ambitious, enthusiastic, and creative students to join exciting collaborations.'], source: 'https://www.altprotein.ca/team-1', image: labUrl },
  '/research': { eyebrow: 'Research · About', title: <>Open questions.<br /><em>Real momentum.</em></>, intro: 'Interdisciplinary research is one of the fastest ways to accelerate the adoption of alternative proteins.', paragraphs: ['Our research involves 5+ professors and 10+ students across mathematics, engineering, and science. We have raised 700k+ CAD to accelerate cultivated meat, particularly fish, development.', 'Our initiatives are supported by the Good Food Institute, New Harvest, and Mitacs. We focus on open-access work that can move the entire field forward.'], source: 'https://www.altprotein.ca/about-1', image: labUrl },
  '/course': { eyebrow: 'Education · Course', title: <>Learn the science<br /><em>behind the shift.</em></>, intro: 'Alternative proteins are transforming how we think about food, science, and the future.', paragraphs: ['Our course creates an accessible entry point into the biology, engineering, ethics, and entrepreneurship behind alternative proteins.', 'Explore the fundamentals, meet the people working in the field, and leave with the context to build something new.'], source: 'https://www.altprotein.ca/course' },
  '/resources/career-guide': { eyebrow: 'Resources · Career guide', title: <>Find your place<br /><em>in the movement.</em></>, intro: 'A career in alternative protein can begin in more places than you think.', paragraphs: ['Our career guide maps the skills, roles, and pathways that are helping build the next generation of food systems.', 'Whether you are a researcher, operator, designer, or communicator, there is meaningful work to do.'], source: 'https://www.altprotein.ca/career-guide-2' },
  '/resources/recipes': { eyebrow: 'Resources · Recipes', title: <>Good food,<br /><em>new possibilities.</em></>, intro: 'The future of food should be delicious as well as sustainable.', paragraphs: ['Discover recipes and ideas that make alternative proteins easy to explore at home.', 'Start small, stay curious, and invite someone else to the table.'], source: 'https://www.altprotein.ca/recipes', image: imageUrl },
  '/resources/alt-protein-in-waterloo': { eyebrow: 'Resources · Waterloo', title: <>Alternative protein<br /><em>in Waterloo.</em></>, intro: 'A growing local ecosystem of students, researchers, and entrepreneurs is changing food from the ground up.', paragraphs: ['Waterloo is a place for ambitious ideas. Our project connects the university community to the global alternative protein movement.', 'Find events, collaborators, and ways to contribute to the work happening right here.'], source: 'https://www.altprotein.ca/' },
  '/resources/cultivating-careers': { eyebrow: 'Resources · Podcast', title: <>Cultivating careers<br /><em>with purpose.</em></>, intro: 'Listen to the people making alternative protein their life’s work.', paragraphs: ['Our podcast explores the unexpected paths into alternative protein and the questions shaping the industry.', 'Tune in for honest conversations with researchers, founders, students, and community builders.'], source: 'https://www.altprotein.ca/cultivating-careers-in-alternative-proteins' },
  '/resources/fermentation-database': { eyebrow: 'Resources · Database', title: <>The fermentation<br /><em>knowledge base.</em></>, intro: 'A practical starting point for exploring one of biology’s oldest and most powerful tools.', paragraphs: ['The fermentation database brings together useful references and shared knowledge for students and researchers.', 'Use it to orient your questions, find new directions, and connect the dots.'], source: 'https://www.altprotein.ca/fermentation-database' },
  '/contact': { eyebrow: 'Contact', title: <>Let’s make<br /><em>something better.</em></>, intro: 'Have an idea, a question, or just want to say hello?', paragraphs: ['We would love to hear from you. Reach the Waterloo Alt Protein Project team and start a conversation about research, education, or collaboration.'], source: 'https://www.altprotein.ca/contact' },
}
